name: Deploy Project
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install Dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm test

  deploy:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install Dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy project
        run: echo "Running deployment ..."
